### ISSUE TITLE
Migrate to scalafix 0.6.0

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/scala-collection-compat#133]

**Comment by olafurpg** [comment]
Now that v0.6.0-M14 is out https://github.com/scalacenter/scalafix/releases/tag/v0.6.0-M14 with support for external rules that are published to Maven I think it's a good time to consider upgrading. There are still no docs on how to upgrade so I'll write something short here

- a minimal but fully functional example of a rule using the latest M14 is here https://github.com/olafurpg/example-scalafix-rule
- I recommend first bumping up the version to M14, then replace all `scala.meta` and `scalafix` imports with `import scala.meta._; import scalafix.v0._`. That should fix most 
compile errors.
- There's a best-effort migration rule for scalafix.g8 generated builds https://github.com/scalacenter/scalafix.g8/tree/master/scalafix the scala-collection-compat build.sbt is quite customized so it may be less helpful.
- by far, most of the breaking changes will relate to the symbol format. I recommend using `SymbolMatcher.normalized` instead of `SymbolMatcher.exact` except in the rare cases where you MUST target an individual method overload. The changes in summary are
  - Before: `scala.Predef.assert(java.lang.String)scala.Unit`
  - After: `scala/Predef.assert()`
  - read notes here https://github.com/scalameta/scalameta/releases/tag/v4.0.0-M6
- I recommend waiting to refactor the rules to use `scalafix.v1` until the builtin rules are using that API.

Once you have upgraded and you want to publish the rules

- publish the rules compiled against 2.12, for example `org.scala-lang.scalafix:collections_2.12:1.0.0`
- users can install sbt-scalafix M14 and update build.sbt
```scala
// build.sbt
inThisBuild(List(
  scalafixDependencies := List(
    "org.scala-lang.scalafix" % "collections_2.12" % "1.0.0"
  )
)
```
- users can run the rules from the sbt shell with

```
// sbt shell
> scalafix class:fix.NewCollections
```
- later down the road, we can use the new service loader functionality so that users can invoke `> scalafix NewCollections` from the shell (no `class:fix.` prefix), but that's not urgent at the moment.
