### ISSUE TITLE
`to(Seq)` doesn't force a stream, where `to[Seq]` did

### ISSUE THREAD

**Issue by martijnhoekstra** [scala/scala-collection-compat#236]
In 2.13, a `Stream#to(Seq)` returns identity. 

In 2.12, `Stream#to[Seq]` returns a `Vector`, as does `Stream#to(Seq)` with compat.

I would argue that's a progression, not a regression, but it does introduce a semantic, potentially breaking change, both in the face of serialization and termination, when the stream isn't forced.

special-casing the scalafix for `Stream#to(Seq)` to `Stream#toVector` would make this change safe and obvious. That could either be obviously wrong or obviously right, both is a win.

Arguably, the same should be done for any `CC#to(Seq)` where `Seq <: CC <: Stream`.

**Comment by julienrf** [comment]
> I would argue that's a progression, not a regression

Both behaviors are legitimate. We could say that `.to(Seq)` always builds a “default” `Seq`, regardless of the type of the source collection. Or we could say that `Stream` is a `Seq` so that’s fine to optimize `.to(Seq)` to return the source collection in that case.

That being said, I have a preference for keeping the behavior we have in 2.13, because it makes `.to(Seq)` consistent with `.toSeq` (which already returned a `Stream` when applied to a `Stream` in 2.12).

The fact that `to(Seq)` behaves differently on 2.13 and on 2.12 (with compat) is a problem, though. We should see if it’s possible to fix it.

**Comment by martijnhoekstra** [comment]
No matter which is done, either `to[Seq]` and `to(Seq)` behave differently on 2.12, or `to(Seq)` behaves differently depending on whether you're on 2.12 or 2.13.

So if I understand you correctly, given the status `2.12 to[Seq] -> Vector` and `2.13 to(Seq) -> (unforced) Stream`, we want to have `2.12 to(Seq) -> (unforced) Stream`?

And still possibly amend the scalafix?

**Comment by julienrf** [comment]
> we want to have `2.12 to(Seq) -> (unforced) Stream`?

Yes.

> And still possibly amend the scalafix?

To rewrite `Stream#.to[Seq]` to `Stream#.to(Vector)`? Yes, why not. We should also rewrite `Stream#.to[LinearSeq]` to `Stream#.to(List)`.
