### ISSUE TITLE
`.to(Col)` vs "unused import" warning

### ISSUE THREAD

**Issue by Daenyth** [scala/scala-collection-compat#240]
I'm not sure how fixable this is, but using `.to(Coll)` on 2.13 causes "unused import" warnings, which is a pain when you have `fatal-warnings` enabled.

example: https://scastie.scala-lang.org/mc1Z3irYQ72gmPNgI96c6g

As a workaround right now I'm disabling the 2.13 version of the flag: `scalacOptions -= "-Wunused:imports"`

**Comment by SethTisue** [comment]
@som-snytt there's a recent ticket on this elsewhere, isn't there?

**Comment by som-snytt** [comment]
I'll check it out. Unused imports usually just works.

**Comment by som-snytt** [comment]
OK, I see what you mean. They [recommend](https://github.com/scala/scala-collection-compat) that you use the "empty" import in 2.13, but of course it is actually unused.

What a conundrum.

Worst case, the warning could special-case the compatibility package under 2.13.

Alternatively, don't warn if an import clause imports nothing. (That is less appealing.)

**Comment by som-snytt** [comment]
I don't know if this is too quick and dirty, but https://github.com/scala/scala/pull/8308

**Comment by NthPortal** [comment]
alternate alternative idea: separate warning flag `-Wunused:empty-imports` (`-Wunused:imports.empty`?) which is set by `-Wunused:imports` by default, but can be separately disabled, so you can do `-Wunused:imports -Wunused:imports.empty:false` (is that the correct syntax?)

**Comment by som-snytt** [comment]
Unfortunately, the import is not empty. Either the source preprocessor or the reporter postprocessor is required. Alternatively, a scalafix that is run as a source generator.

**Comment by SethTisue** [comment]
is this `-Wconf`/`@nowarn`able?

**Comment by valencik** [comment]
I don't think `@nowarn` works on imports, at least I couldn't get scalac to like any of my attempts.

`-Wconf` seems more promising but I am not sure how to match exactly the warning we have.
Consider:

```
sbt:http4s> core / compile
[info] compiling 219 Scala sources to /home/andrew/grabbed/http4s/core/target/scala-2.13/classes ...
[warn] /home/andrew/grabbed/http4s/core/src/main/scala/org/http4s/Query.scala:33:32: Unused import
[warn] import scala.collection.compat._
[warn]                                ^
[warn] one warning found
```

Running `set scalacOptions in core ++= Seq("-Wconf:cat=unused-imports:silent")` in sbt followed by `core / compile` does work, but this is too much, we're ignoring all unused imports.

Sadly `set scalacOptions in core ++= Seq("-Wconf:msg=import scala\.collection\.compat\._:silent")` does not work, because our warning [message is actually just `Unused import`](https://github.com/scala/scala/blob/2.13.x/src/compiler/scala/tools/nsc/typechecker/Contexts.scala#L98), it doesn't include any of the other output.

**Comment by som-snytt** [comment]
FSR no one mentioned `-Yimports`, which manipulates the root contexts (not really imports) and is not subject to unused warnings. `-Yimports:java.lang,scala,scala.Predef,scala.collection.compat`.

I guess the reason is that the option is not available for 2.12. How very unfortunate!

If the import were needed only on 2.13, then it would work as expected.

At least I had an opportunity to re-read https://www.scala-sbt.org/1.x/docs/Cross-Build.html yet again but I forgot to notify Guinness book of world records before I attempted it. Maybe I can still get a mention in Ripley's Believe it or not.

**Comment by som-snytt** [comment]
I spent some time with `-Wconf:help`, and I think `site` is workable, though it may be ungainly.

```
crossScalaVersions := Seq("2.12.12", "2.13.4")

libraryDependencies += "org.scala-lang.modules" %% "scala-collection-compat" % "2.4.1"

// gratuitous, as the import is required for compiling under 2.12
Compile / scalacOptions ++= {
  CrossVersion.partialVersion(scalaVersion.value) match {
    case Some((2, n)) if n <= 12 => Seq("-Xlint")
    case _                       => Seq("-Xlint", raw"-Wconf:cat=unused-imports&site=p\.(Main|C):s,any:wv")
    //case _                       => Seq("-Xlint", "-Yimports:java.lang,scala,scala.Predef,scala.collection.compat")
  }
}

Compile / scalacOptions ++= Seq("-Xfatal-warnings")
```
with source file
```
package p

object Main extends App {
  import scala.collection.compat._
  val xs = Seq("a","b","c")
  println(xs.to(List))
}

class C {
  import scala.collection.compat._
  val xs = Seq("a","b","c")
  def f = xs.to(List)
}
```
There is a trade-off between specificity of import and complexity of the `-Wconf:site` pattern.

Issue for origin:

https://github.com/scala/bug/issues/12326

**Comment by som-snytt** [comment]
One way to ensure your package is used on import:
```
    package object compat {
      implicit def $conforms[A]: A => A = <:<.refl
    }
```

**Comment by som-snytt** [comment]
The linked ticket was fixed. I am empowered to close this ticket, so I will do so in that context.

**Comment by SethTisue** [comment]
to save others some digging: https://github.com/scala/scala/pull/9939 added support for `origin=` filtering on unused imports

**Comment by som-snytt** [comment]
origin is https://github.com/scala/scala3/pull/21404 and I'll check that imports uses it at https://github.com/scala/scala3/pull/20894
