### ISSUE TITLE
Drop 2.12's scala.annotation.nowarn once 2.12.13 is out

### ISSUE THREAD

**Issue by dwijnand** [scala/scala-collection-compat#397]
See https://github.com/scala/scala-lang/pull/1184#discussion_r534666118

2.12.13 is coming out imminently  (today?).  Once it's out, probably best when bumping to 2.12.13, it would be good to move that noop to 2.11 only.

But two scenarios to think about:

1. users that upgrade `scalaVersion` but not `scala-collection-compat` (or if we don't implement this change): it's unclear what classfile for `@nowarn` they'll class load, which could break the configurable warning feature

2. users that upgrade `scala-collection-compat` (with this implemented) but not `scalaVersion`: won't have a `@nowarn` in they're classpath any more... 😕 🤔 ...

**Comment by lrytz** [comment]
>     1. users that upgrade `scalaVersion` but not `scala-collection-compat` (or if we don't implement this change): it's unclear what classfile for `@nowarn` they'll class load, which could break the configurable warning feature

are you sure things would break? even if
```
lazy val NowarnClass                = getClassIfDefined("scala.annotation.nowarn")
```
picks up the classfile from collection-compat, things could still work.

Ah, the problem is that the one here `extends StaticAnnotation`, but the one in 2.12.13 `extends ClassfileAnnotation`, so the 2.12.13 compiler would look for the string parameter in the wrong spot (`annotationInfo.assocs` instead of `annotationInfo.args`).

**Comment by SethTisue** [comment]
@lrytz want to do one more round of thinking about this now that 2.12.13 is out...? I'm happy to pull publishing levers as needed once we're sure what the right thing is.

**Comment by lrytz** [comment]
Maybe we can find some workaround by making `scala.annotation.nowarn` a type alias in this library?

Another option is to add this patch to the compiler, it would make the 2.12 nowarn implementation work with the annotation from this library (which `extends StaticAnnotation` instead of `ClassfileAnnotation`). The patch is from some other WIP branch of mine. https://github.com/scala/scala/commit/6816ff0fe228885cc5e770856107c377060ddb1b. This would only be in 2.12.14 though.

Another option is to change the annotation in this library to `extends ClassfileAnnotation`, i.e., make it identical to the one in 2.12.13.

**Comment by SethTisue** [comment]
> Another option is to change the annotation in this library to extends ClassfileAnnotation, i.e., make it identical to the one in 2.12.13.

Is there some downside to that?

**Comment by lrytz** [comment]
I can't think of any issues that change would cause.

**Comment by NthPortal** [comment]
is that binary compatible?

**Comment by SethTisue** [comment]
#417

**Comment by SethTisue** [comment]
fyi @ghik (not sure if it matters over in your repo)
